# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
        ('orders', '0001_initial'),
        ('messaging', '0001_initial'),
        ('teacher', '0001_initial'),
        ('opening', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_tuition', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('datebetween', models.IntegerField(blank=True, null=True)),
                ('cnc', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('gradebefore', models.CharField(blank=True, max_length=20, null=True)),
                ('gradeafter', models.CharField(blank=True, max_length=20, null=True)),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('reviewcomment', models.TextField(blank=True, max_length=500, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.Level_Expertise')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opening.Opening')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.Subject_Expertise')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
