# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_range', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('job_active', models.BooleanField(default=True)),
                ('group_tuition', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('trial_acc', models.BooleanField(default=False)),
                ('hiring_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variables.Level_Expertise')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variables.Region')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variables.Subject_Expertise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
