# Generated by Django 2.2 on 2020-09-15 16:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'XXXX-XXXX'.", regex='^\\d{4}-\\d{4}$')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('group_tuition', models.BooleanField(default=False)),
                ('website_url', models.CharField(blank=True, max_length=60, null=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('salary_negotiable', models.BooleanField(default=False)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('review_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('trial_acc', models.BooleanField(default=False)),
                ('docs_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=teacher.models.image_upload_to)),
                ('doc1', models.ImageField(blank=True, null=True, upload_to=teacher.models.doc_upload_to1)),
                ('doc1description', models.CharField(blank=True, max_length=60, null=True)),
                ('doc2', models.ImageField(blank=True, null=True, upload_to=teacher.models.doc_upload_to2)),
                ('doc2description', models.CharField(blank=True, max_length=60, null=True)),
                ('doc3', models.ImageField(blank=True, null=True, upload_to=teacher.models.doc_upload_to3)),
                ('doc3description', models.CharField(blank=True, max_length=60, null=True)),
                ('doc4', models.ImageField(blank=True, null=True, upload_to=teacher.models.doc_upload_to4)),
                ('doc4description', models.CharField(blank=True, max_length=60, null=True)),
                ('doc5', models.ImageField(blank=True, null=True, upload_to=teacher.models.doc_upload_to5)),
                ('doc5description', models.CharField(blank=True, max_length=60, null=True)),
                ('doc6', models.ImageField(blank=True, null=True, upload_to=teacher.models.doc_upload_to6)),
                ('doc6description', models.CharField(blank=True, max_length=60, null=True)),
                ('education', models.ManyToManyField(to='variables.Education')),
                ('education_school', models.ManyToManyField(to='variables.Education_School')),
                ('educational_level', models.ManyToManyField(to='variables.Educational_Level')),
                ('expertise_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.Expertise_Type')),
                ('first_level', models.ManyToManyField(blank=True, to='variables.Level_Expertise')),
                ('first_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.Subject_Expertise')),
                ('region', models.ManyToManyField(to='variables.Region')),
                ('second_level', models.ManyToManyField(blank=True, related_name='level2', to='variables.Level_Expertise')),
                ('second_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='variables.Subject_Expertise')),
                ('third_level', models.ManyToManyField(blank=True, related_name='level3', to='variables.Level_Expertise')),
                ('third_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='variables.Subject_Expertise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
